### ISSUE TITLE
Ban bug

### ISSUE THREAD

**Issue by tombola46** [OneAddictions/Jinx-Issues#1]
Hi if I get banned for cheating and then I use /pardon and I want to join I get this error : https://pastebin.com/DgTTYN7x and it will disconnect me with every account or name. I dont know if this is bug in your anticheat but can you help me ? (EDIT: After restart is everything okay) (EDIT2: oh sorry xD It was by /relaod)

**Comment by OneAddictions** [comment]
This aint a anticheat error, its /reload, and id recommend not using the anticheat the moment, as there are plenty of bugs, and i also have to fix an issue with it
